# Generated by Django 5.1.2 on 2025-02-14 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='confirmation_cde',
            new_name='confirmation_code',
        ),
    ]
