# Generated by Django 5.1.2 on 2025-02-15 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_rename_confirmation_cde_userprofile_confirmation_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
